# Generated by Django 3.2.3 on 2021-07-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name1', models.CharField(max_length=15)),
                ('d_group_blood1', models.CharField(max_length=5)),
                ('d_unit1', models.IntegerField()),
                ('d_age1', models.IntegerField()),
                ('d_phone_no1', models.BigIntegerField()),
                ('d_email1', models.EmailField(max_length=254)),
                ('d_date1', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=15)),
                ('p_group_blood', models.CharField(max_length=5)),
                ('p_unit', models.IntegerField()),
                ('p_age', models.IntegerField()),
                ('p_phone_no', models.BigIntegerField()),
                ('p_email', models.EmailField(max_length=254)),
                ('p_date', models.DateTimeField()),
            ],
        ),
    ]
